"""Initial schema

Revision ID: 1b6c523ba14b
Revises: 
Create Date: 2026-09-03 11:22:49.845960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b6c523ba14b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('economic_series',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fred_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('frequency', sa.String(length=10), nullable=True),
    sa.Column('units', sa.Text(), nullable=True),
    sa.Column('policy_dimension', sa.String(length=30), nullable=True),
    sa.Column('claim_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fred_id')
    )
    op.create_table('fomc_meetings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_date', sa.Date(), nullable=False),
    sa.Column('statement_date', sa.Date(), nullable=True),
    sa.Column('minutes_date', sa.Date(), nullable=True),
    sa.Column('rate_decision', sa.String(length=20), nullable=True),
    sa.Column('target_rate_low', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('target_rate_high', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('has_sep', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_date')
    )
    op.create_table('economic_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('series_id', sa.UUID(), nullable=True),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('vintage_date', sa.Date(), nullable=True),
    sa.Column('is_revised', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['economic_series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fomc_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=True),
    sa.Column('doc_type', sa.String(length=20), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['fomc_meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting_comparisons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('base_meeting_id', sa.UUID(), nullable=True),
    sa.Column('comp_meeting_id', sa.UUID(), nullable=True),
    sa.Column('text_diff', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('semantic_changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_interpretation', sa.Text(), nullable=True),
    sa.Column('stance_delta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['base_meeting_id'], ['fomc_meetings.id'], ),
    sa.ForeignKeyConstraint(['comp_meeting_id'], ['fomc_meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('inflation_assessment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('labor_assessment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('growth_assessment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('financial_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('forward_guidance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('overall_stance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_llm_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extraction_model', sa.String(length=50), nullable=True),
    sa.Column('extraction_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['fomc_documents.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['fomc_meetings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('policy_assessments')
    op.drop_table('meeting_comparisons')
    op.drop_table('fomc_documents')
    op.drop_table('economic_observations')
    op.drop_table('fomc_meetings')
    op.drop_table('economic_series')
    # ### end Alembic commands ###
