"""Add MarketReaction

Revision ID: 22b33503dac0
Revises: 1b6c523ba14b
Create Date: 2026-09-04 10:40:13.768516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22b33503dac0'
down_revision: Union[str, Sequence[str], None] = '1b6c523ba14b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_reactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=True),
    sa.Column('spy_change_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tlt_change_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['fomc_meetings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id')
    )
    # op.drop_table('document_chunks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('meeting_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('doc_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('meeting_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('word_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['fomc_documents.id'], name=op.f('document_chunks_document_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['fomc_meetings.id'], name=op.f('document_chunks_meeting_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('document_chunks_pkey')),
    sa.UniqueConstraint('document_id', 'chunk_index', name=op.f('unique_chunk'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_chunks_vector'), 'document_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '10'}, postgresql_using='ivfflat')
    op.create_index(op.f('idx_chunks_fts'), 'document_chunks', [sa.literal_column("to_tsvector('english'::regconfig, text)")], unique=False, postgresql_using='gin')
    op.drop_table('market_reactions')
    # ### end Alembic commands ###
